INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('1', 'AMAZONAS');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('2', 'ANTIOQUIA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('3', 'ARAUCA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('4', 'ATLÁNTICO');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('5', 'BOLÍVAR');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('6', 'BOYACÁ');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('7', 'CALDAS');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('8', 'CAQUETÁ');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('9', 'CASANARE');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('10', 'CAUCA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('11', 'CESAR');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('12', 'CHOCÓ');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('13', 'CÓRDOBA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('14', 'CUNDINAMARCA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('15', 'GUAINÍA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('16', 'GUAVIARE');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('17', 'HUILA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('18', 'LA GUAJIRA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('19', 'MAGDALENA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('20', 'META');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('21', 'NARIÑO');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('22', 'NORTE DE SANTANDER');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('23', 'PUTUMAYO');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('24', 'QUINDÍO');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('25', 'RISARALDA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('26', 'SAN ANDRÉS Y ROVIDENCIA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('27', 'SANTANDER');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('28', 'SUCRE');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('29', 'TOLIMA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('30', 'VALLE DEL CAUCA');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('31', 'VAUPÉS');
INSERT INTO akuavida.departamento (idDepartamento , Nombre_Departamento) VALUES ('32', 'VICHADA');